In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "$AAPL"
tweets = []
limit = 10

# stock list
list_of_stocks = pd.read_html('https://en.wikipedia.org/wiki/Nasdaq-100')[4]['Ticker'].to_list()
stock_list = []

# add cashtag to filter for stocks
for stock in list_of_stocks:
    stock_list.append(f'${stock}')

for stock in stock_list:
    for tweet in sntwitter.TwitterSearchScraper(stock).get_items():
        if len(tweets) == limit:
            break
        else:
            tweets.append([tweet.date, tweet.username, tweet.content])
    print(f'{stock} completed')
            
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])

/tmp/ipykernel_4280/461667455.py:21: FutureWarning: username is deprecated, use user.username instead
  tweets.append([tweet.date, tweet.username, tweet.content])

$ATVI completed
$ADBE completed
$ADP completed
$ABNB completed
$ALGN completed
$GOOGL completed
$GOOG completed
$AMZN completed
$AMD completed
$AEP completed
$AMGN completed
$ADI completed
$ANSS completed
$AAPL completed
$AMAT completed
$ASML completed
$AZN completed
$TEAM completed
$ADSK completed
$BKR completed
$BIIB completed
$BKNG completed
$AVGO completed
$CDNS completed
$CHTR completed
$CTAS completed
$CSCO completed
$CTSH completed
$CMCSA completed
$CEG completed
$CPRT completed
$CSGP completed
$COST completed
$CRWD completed
$CSX completed
$DDOG completed
$DXCM completed
$FANG completed
$DLTR completed
$EBAY completed
$EA completed
$ENPH completed
$EXC completed
$FAST completed
$FISV completed
$FTNT completed
$GILD completed
$GFS completed
$HON completed
$IDXX completed
$ILMN completed
$INTC completed
$INTU completed
$ISRG completed
$JD completed
$KDP completed
$KLAC completed
$KHC completed
$LRCX completed
$LCID completed
$LULU completed
$MAR completed
$MRVL completed
$MELI completed
$META completed
$MCHP completed
$MU completed
$MSFT completed
$MRNA completed
$MDLZ completed
$MNST completed
$NFLX completed
$NVDA completed
$NXPI completed
$ORLY completed
$ODFL completed
$PCAR completed
$PANW completed
$PAYX completed
$PYPL completed
$PEP completed
$PDD completed
$QCOM completed
$REGN completed
$RIVN completed
$ROST completed
$SGEN completed
$SIRI completed
$SBUX completed
$SNPS completed
$TMUS completed
$TSLA completed
$TXN completed
$VRSK completed
$VRTX completed
$WBA completed
$WBD completed
$WDAY completed
$XEL completed
$ZM completed
$ZS completed

In [13]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "$AAPL"
tweets = []
limit = 100

for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.username, tweet.content, query])
    
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'Cashtag'])

/tmp/ipykernel_4280/2334208376.py:12: FutureWarning: username is deprecated, use user.username instead
  tweets.append([tweet.date, tweet.username, tweet.content, query])

In [14]:
df

,Date,User,Tweet,Cashtag
0,2022-12-31 18:14:13+00:00,_JaxCapital,Headlines from the future: \n\nT-Phone (@Tesla...,$AAPL
1,2022-12-31 18:14:11+00:00,HelenBurstin,@Farzad_MD @Apple I was very happy to see them!,$AAPL
2,2022-12-31 18:13:50+00:00,Melanie43031650,$AAPL Trade ideaðŸ’¡\nhttps://t.co/eNNzpYouxW\n$A...,$AAPL
3,2022-12-31 18:13:39+00:00,manojtl28,@OnlyCitrus @Apple Isopropyl alcohol?,$AAPL
4,2022-12-31 18:13:26+00:00,mariatriandos,@Apple Thanks for sending me defective product...,$AAPL
...,...,...,...,...
95,2022-12-31 17:48:58+00:00,kaedecoy,cyan heart @Apple,$AAPL
96,2022-12-31 17:48:57+00:00,ElliotThereal,@healthierwithu @Apple how much they pay you t...,$AAPL
97,2022-12-31 17:48:31+00:00,1sdkid,"@apple I want to continue to buy iPods, but I ...",$AAPL
98,2022-12-31 17:48:18+00:00,harbinger__the,HELLO MY BATTERY JUST WENT FROM 28% TO 13% IN ...,$AAPL
99,2022-12-31 17:48:11+00:00,Benzkidd5,Dear @Apple â€¦ why when I hit delete and report...,$AAPL

In [25]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

tweets = []
list_of_stocks = pd.read_html('https://en.wikipedia.org/wiki/Nasdaq-100')[4]['Ticker'].to_list()
list_of_stocks = [f'${stock}' for stock in list_of_stocks]

for stock in stock_list:
    limit = 0
    for tweet in sntwitter.TwitterSearchScraper(stock).get_items():
        if limit == 10:
            break
        else:
            tweets.append([tweet.date, tweet.user.username, tweet.content, stock])
            limit += 1
    print(f'{stock} done')
        
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'Cashtag'])

$ATVI done
$ADBE done
$ADP done
$ABNB done
$ALGN done
$GOOGL done
$GOOG done
$AMZN done
$AMD done
$AEP done
$AMGN done
$ADI done
$ANSS done
$AAPL done
$AMAT done
$ASML done
$AZN done
$TEAM done
$ADSK done
$BKR done
$BIIB done
$BKNG done
$AVGO done
$CDNS done
$CHTR done
$CTAS done
$CSCO done
$CTSH done
$CMCSA done
$CEG done
$CPRT done
$CSGP done
$COST done
$CRWD done
$CSX done
$DDOG done
$DXCM done
$FANG done
$DLTR done
$EBAY done
$EA done
$ENPH done
$EXC done
$FAST done
$FISV done
$FTNT done
$GILD done
$GFS done
$HON done
$IDXX done
$ILMN done
$INTC done
$INTU done
$ISRG done
$JD done
$KDP done
$KLAC done
$KHC done
$LRCX done
$LCID done
$LULU done
$MAR done
$MRVL done
$MELI done
$META done
$MCHP done
$MU done
$MSFT done
$MRNA done
$MDLZ done
$MNST done
$NFLX done
$NVDA done
$NXPI done
$ORLY done
$ODFL done
$PCAR done
$PANW done
$PAYX done
$PYPL done
$PEP done
$PDD done
$QCOM done
$REGN done
$RIVN done
$ROST done
$SGEN done
$SIRI done
$SBUX done
$SNPS done
$TMUS done
$TSLA done
$TXN done
$VRSK done
$VRTX done
$WBA done
$WBD done
$WDAY done
$XEL done
$ZM done
$ZS done

In [26]:
df

,Date,User,Tweet,Cashtag
0,2022-12-31 17:59:50+00:00,Morriso54219277,$ATVI Top analyst price target for next week...,$ATVI
1,2022-12-31 17:46:18+00:00,Morriso54219277,$ATVI Top analyst price target for next week...,$ATVI
2,2022-12-31 17:18:53+00:00,Rosie94174146,$ATVI Top analyst price target for next week...,$ATVI
3,2022-12-31 17:08:27+00:00,Rosie94174146,$ATVI Top analyst price target for next week...,$ATVI
4,2022-12-31 15:39:54+00:00,161point8,Props to any stock pickers that found some gre...,$ATVI
...,...,...,...,...
1005,2022-12-31 16:54:21+00:00,Marlin_Capital,I warned about Bubble Stocks many times during...,$ZS
1006,2022-12-31 16:50:58+00:00,LillianGeary5,$zs ALL THESE LEVELS POSTED AHEAD OF TIME BE...,$ZS
1007,2022-12-31 16:47:17+00:00,iamluka01,"@davey_juice Incredible, I love high insider o...",$ZS
1008,2022-12-31 16:38:56+00:00,davey_juice,$zs two co founders own 39-40% of the float of...,$ZS
1009,2022-12-31 16:33:48+00:00,Mrjonso64929896,$zs Trade the US stock market? Before they h...,$ZS